version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 20.0.0
        commands:
            - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
            - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
    pre_build:
        commands:
            - echo log in to Amazon ECR...
            - aws --version
            - echo $AWS_DEFAULT_REGION
            - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
            - echo $AWS_ACCOUNT_ID
            - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 688567280963.dkr.ecr.us-east-2.amazonaws.com
            - REPOSITORY_URI=688567280963.dkr.ecr.us-east-2.amazonaws.com/scdindra
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - IMAGE_TAG=${COMMIT_HASH:=latest}
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker image.
            - docker build -t $REPOSITORY_URI:latest . --build-arg ENVIRONMENT=$ENVIRONMENT
            - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Push image to ECR
            - docker push $REPOSITORY_URI:latest
            - docker push $REPOSITORY_URI:$IMAGE_TAG
            - echo process successfully...
